name: Conditional Basic Execution Workflow

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Project
        id: build
        run: |
          echo "Building the project..."
          exit 1  # Simulate a build failure for testing

    # Conditional execution at the job level
    - name: Run if job fails
      if: failure()  # This checks if the entire job has failed
      run: |
        echo "Job has failed. The build project step failed."
