name: Conditional Execution Workflow

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Project
        run: |
          echo "Building the project..."
          exit 1  # Simulate a build failure for testing

  job2:
    runs-on: ubuntu-latest
    needs: job1  # This job depends on job1
    steps:
      - name: Run Tests
        run: |
          echo "Running tests..."
          exit 0  # This can be modified based on your testing logic

  job3:
    runs-on: ubuntu-latest
    needs: job1  # This job also depends on job1
    if: failure()  # This job runs only if job1 fails
    steps:
      - name: Notify Build Failure
        run: echo "Job1 has failed. Executing Job3 for failure handling."

  job4:
    runs-on: ubuntu-latest
    needs: job2  # This job depends on job2
    steps:
      - name: Step in Job2
        id: step_in_job2
        run: |
          echo "This is a step in Job2."
          exit 1  # Simulate a failure for testing

      - name: Execute if Step in Job2 Fails
        if: steps.step_in_job2.conclusion == 'failure'  # Runs only if the previous step fails
        run: echo "Step in Job2 has failed. Running this step."

