name: Day2 Env, With

on: 
 push:
 workflow_dispatch:

env:
  WORKFLOW_LEVEL_ENV: Monday

jobs:
     
  greeting_job:
    runs-on: ubuntu-latest
    env: 
      Greeting: Hello 

    steps: 
      - name: "Say Hello Mona it's Monday" 
        env: 
          First_Name: Mona 

        run: | 
          echo "$Greeting $First_Name. Today is $WORKFLOW_LEVEL_ENV!"
          echo "${{ env.First_Name }}  "

  input_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Login to DockerHub
        do it in the session
        
       