name: Day2 Variables and Secrets

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use secret
        run: echo "The secret value is ${{ secrets.MY_SECRET }}"  # Using the secret


      - name: Use secret
        run: echo "The secret value is $SECRET"  # Using the secret
        env:
          SECRET: ${{ secrets.MY_SECRET }}  # Accessing the secret


      - name: Print Repository Variables
        
        run: |
          echo "Greeting: ${{ vars.GREETING }}"
          echo "Environment: ${{ vars.ENVIRONMENT }}"  
      
      - name: Print Repository Variables
        run: |
          echo "my variable: ${{ vars.MY_VAR }}"
          echo "my environment: ${{ vars.MY_SECRET }}"       
          
          
       
      