name: Day2 inbuilt github secrets

on: [push]

# Setting permissions for all jobs in this workflow
permissions:
  contents: read  # Read access to repository contents
  issues: write    # Write access to issues
  pull-requests: read  # Read access to pull requests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use GITHUB_TOKEN
        run: |
          echo "Using GITHUB_TOKEN with specified permissions"



# name: Workflow with Restricted GITHUB_TOKEN Permissions

# on: [push]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     # Set permissions for GITHUB_TOKEN
#     permissions:
#       contents: read  # Allows read access to repository contents
#       issues: write    # Allows write access to issues
#       pull-requests: write  # Allows write access to pull requests

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Use GITHUB_TOKEN
#         run: |
#           echo "Using GITHUB_TOKEN with restricted permissions"
#           echo "Token: ${{ secrets.GITHUB_TOKEN }}"
