name: Day 3 Calling Composite Actions

on: [push, workflow_dispatch]

jobs:
    call-composite-action:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout the repository
          uses: actions/checkout@v4

        - name: Call  print_actions
          uses: ./.github/actions/print_message
          with:
              message: "Hello from composite action!"
              SECRET_TOKEN: ${{ secrets.GITHUB_TOKEN }}