name: Day3 Sharing Data

on: [push, workflow_dispatch]

jobs:

    uploading_artifact:
        runs-on: ubuntu-latest

        steps:
          - name: Create Text file
            run: | 
              echo "This is a text file" > file.txt
    
          - name: Upload Artifact
            uses: actions/upload-artifact@v4
            with:
              path: file.txt 
                             
    downloading_artifact:
        runs-on: ubuntu-latest
        needs: uploading_artifact

        steps:
          - name: Download Artifact
            uses: actions/download-artifact@v4
            with:
              path: file.txt

#  cd file.txt/artifact/file.txt

          - name: List files
            run: |
                
                ls -la
                cd artifact
                ls -la

###############################################

    sharing_data_between_steps:
        runs-on: ubuntu-latest
        
        steps:
          - name: Create Variables
            run: |
                echo "MY_VAR=Variabel from step" >> $GITHUB_ENV

          - name: Print Variables
            run: |
                echo "MY_VAR: $MY_VAR"
                echo "----------------------------"
                echo "GITHUB_ENV: $GITHUB_ENV"
                echo "----------------------------"
                echo "MY_VAR: ${{ env.MY_VAR }}"
                echo "----------------------------"

################################################# 

    job1:
      runs-on: ubuntu-latest
      outputs:
        data: ${{ steps.step1.outputs.data }}
      steps:
        - name: Generate Data
          id: step1
          run: |
            echo "data=hello from job1" >> $GITHUB_OUTPUT

    job2:
      runs-on: ubuntu-latest
      needs: job1
      steps:
        - name: Use Data from job1
          run: |
            echo "Data from job1: ${{ needs.job1.outputs.data }}"