name: Day 3 Calling Composite Actions

on: [workflow_dispatch]

jobs:
    call-composite-action:
        runs-on: ubuntu-latest

        steps:
        - name: Call  print_actions
          uses: ../actions/print_message@main
          with:
              message: "Hello from composite action!"
              SECRET_TOKEN: ${{ secrets.GITHUB_TOKEN }}