name: Day3 Matrix Strategy

on: push

jobs:
    build:
        runs-on: [self-hosted]

        strategy:
            matrix:
                runner: [my_runner1, my_runner2]

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Run a one-line script
          run: echo "Hello, world!"