name: Day3 Sharing Data

on: [push, workflow_dispatch]

jobs:

    uploading_artifact:
        runs-on: ubuntu-latest

        steps:
          - name: Create Text file
            run: | 
              echo "This is a text file" > file.txt
              ls

          - name: List files
            run: ls       
    
        #   - name: Upload Artifact
        #     uses: actions/upload-artifact@v4
        #     with:
        #       name: file.txt 
                             
    downloading_artifact:
        runs-on: ubuntu-latest
        needs: uploading_artifact

        steps:
          - name: Download Artifact
            uses: actions/download-artifact@v4
            with:
              name: file.txt
    
          - name: Print Artifact
            run: cat file.txt    
        