name: Day 3 Calling Workflow

on:
    workflow_dispatch:

jobs:
    call_another_workflow:
        uses: ./.github/workflows/day3called_workflow.yml
        with:
            input1: "This is input from calling workflow"
        secrets:
            secret1: ${{ secrets.GITHUB_TOKEN }}