name: Day3 needs keyword

on: [push, workflow_dispatch]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "build"
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "test"
  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - run: echo "deploy"

    

