name: Day3 Sharing Data

on: [push, workflow_dispatch]

jobs:

    uploading_artifact:
        runs-on: ubuntu-latest

        steps:
          - name: Create Text file
            run: | 
              echo "This is a text file" > file.txt
    
          - name: Upload Artifact
            uses: actions/upload-artifact@v4
            with:
              path: file.txt 
                             
    downloading_artifact:
        runs-on: ubuntu-latest
        needs: uploading_artifact

        steps:
          - name: Download Artifact
            uses: actions/download-artifact@v4
            with:
              path: file.txt
    
          - name: List files
            run: |
                ls -la
                