name: Day3 Webhook Event Trigger

on:
    repository_dispatch:
        types:
            - custom-event

jobs:
    webhook-event-job:
        runs-on: ubuntu-latest

        steps:
            - name: Step1
              run: | 
                echo "You have triggered a custom event"
                echo "Received event type: ${{ github.event.action }}"
                echo "Custom Payload: ${{ github.event.client_payload.key1 }}"

# curl -X POST -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token ghp_hamar_token" -d "{\"event_type\": \"custom-event\", \"client_payload\": {\"key1\": \"value1\"}}" https://api.github.com/repos/pranavjames/github-training/dispatches                

            
              
               