name: Day3 needs keyword

on: [push, workflow_dispatch]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "build"
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "test"
  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - run: echo "deploy"

  uploading_artifact:
    runs-on: ubuntu-latest
    needs: [build, test, deploy]
    steps:
      - name: Create Text file
        run: echo "This is a text file" > file.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: file.txt 
            
          
  downloading_artifact:
    runs-on: ubuntu-latest
    needs: uploading_artifact
    steps:

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: file.txt

      - name: Print Artifact
        run: cat file.txt    
    

