name: Basic Conditions

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
      - branch1

  pull_request:
    branches:
      - main # Trigger on pull request to main branch

      
jobs:
  job1:
    runs-on: [ ubuntu-latest ]
    
    steps:


      - name: "Step1"
        run: |
          echo "Step1"

      - name: "Step2"
        if:  ${{ github.ref }} == "refs/heads/main"
        run: |
          echo "Step2"
          echo "github.ref => ${{ github.ref }}"

          echi "Print Event : ${{ github.event_name}}"

        
      - name: "Step 3"
        if: ${{ github.event_name == 'pull_request' }}  # Condition for pull requests
        run: |
          echo "Step 4: This step runs only for pull requests targeting the main branch."  
        
          


