name: Basic Conditions

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
      - branch1

  pull_request:
    branches:
      - main # Trigger on pull request to main branch

      
jobs:
  job1:
    runs-on: [ ubuntu-latest ]
    
    steps:


      - name: "Step1"
        run: |
          echo "Step1"

      - name: "Step2"
        if:  ${{ github.ref }} == "refs/heads/main"
        run: |
          echo "Step2"
          echo "github.ref => ${{ github.ref }}"
          echo "Current Branch: ${GITHUB_REF#refs/heads/}"
        
          


