name: Training Basic Main Workflow 
on:
  push:
    branches:
      - main
  pull_request: 
    types: ["opened"]
    branches:
      - main 
  
#   workflow_dispatch:       
      



jobs:
    java-setup:
        runs-on: [ubuntu-latest]
        steps:
          - uses: actions/checkout@v4

          - name: Setup Java
            uses: actions/setup-java@v4
            with:
              distribution: 'oracle' 
              java-version: '21'
          
          - name: Print Java Version
            run: |
                 java --version    
  